#!/bin/bash
java -jar /home/tyler/Development/work/util/map-sobject/target/mapsobject-jar-with-dependencies.jar -o s,00D0q0000000wSs,cit@kuebix.com.tlundstrom,CSkuebix2015,sAzqyKj1fTtjUUaLLQTfXU0i -n Shipment_Accessorials__c -s -u
