#!/bin/bash
notify-send -i "$HOME/Pictures/kuebix-symbol.png" \
"Tomcat" \
" 
Redeploying portal-manager
 "
 cd $HOME/Development/work/portal/portal-code/portal-manager
 mvn tomcat7:redeploy > $HOME/Development/work/portal/portal-code/pm_redeploy.log
 PM_RD_T_TIME=$(cat $HOME/Development/work/portal/portal-code/pm_redeploy.log | grep -i "total time")
 notify-send  -i "$HOME/Pictures/kuebix-symbol.png" \
 "Tomcat" \
 " 
 portal-manager redeployed 

 $PM_RD_T_TIME
  "
